### PR TITLE
fix(bi-link): Invalidation of title reference

### PR DESCRIPTION
**Pull request by LincZero**
如果遇到 `[[#title]]` 的情况，会导致编译报错

### CODE REVIEW

**Review by LittleSound — COMMENTED** [review]
Thank you for the PR. write the unit test code to ensure that the feature remains fixed in future versions.

Please check [index.test.ts](https://github.com/nolebase/integrations/blob/main/packages/markdown-it-bi-directional-links/src/index.test.ts) and you will see how to write unit tests, write your tests there.

**Comment by LincZero** [comment]
I know, thanks.

However, I thought there was no syntax to support '[[#title]]', so I simply excluded it from the RE. But now it seems that '[[page#title]]' is supported (which is why I failed the unit test), but not the '[[title]]' case of ignoring page (which refers to a title of the article).

This also meant that I needed to use a different solution to solve the bug. I don't have enough time today. I may come back to repair it in a couple of days.

**Comment by nekomeowww** [comment]
No worries, take your time.

**Review by nekomeowww — APPROVED** [review]

**Comment by nekomeowww** [comment]
LGTM, thanks.

**Pull request merged**
